Removed new_from_db function, updated README file to be more clear fo…
learn-co-curriculum/python-p3-translating-from-orms-to-sqlalchemy-lab pull request #11
Opened 2023-03-21 14:58 UTC by ianstrom

…r environment setup

2023-03-21 14:59 UTC, ianstrom commented
Removed new_from_db function, updated README file to be more clear for environment setup

2023-03-21 15:34 UTC, professor-ben commented on README.md
I'm a bit confused on this one- the Pipfile is in the repo root, so that should be where this command is run from. Should you be `cd`ing into `lib/` right afterward instead?

2023-03-21 15:36 UTC, professor-ben requested changes
The directory change seems to be out of place in this pull request- you'll need to be in the repo root to run `pipenv install`. Can you re-check that this switch needs to happen and where it should be placed in the instructions?

2023-03-22 17:48 UTC, ianstrom commented on README.md
Hi Ben, sorry for the delay, I am just seeing these messages. I originally added this to the README file because I had been running pipenv install and pipenv shell in my vscode terminal. When running pipenv install in the root directory of vscode, you will receive an error:

 pyenv: pipenv: command not found

The `pipenv' command exists in these Python versions:
  3.8.13
  3.8.16 

I just tested this again and if you are in the os terminal, pipenv install and pipenv shell works fine. It is only when you're in the vscode terminal that you receive an error. To fix this, I first cd'ed into the lib directory and then pipenv install && pipenv shell will work. This has not been the case in other labs so I am not quite sure what is at play here.

Either way, clarifying to a student to cd into lib/ before they use pytest would be a very helpful addition.

Thank you so much for taking the time to improve the curriculum!

2023-03-27 14:08 UTC, merged